### ISSUE TITLE
Font not loading in vercel deplyoment

### ISSUE THREAD

**Issue by leetdavid** [bilbyai/intelligence-platform#63]
![image](https://github.com/bilbyai/intelligence-platform/assets/9511823/799485f4-8314-4021-92f2-008130ecf75f)

![image](https://github.com/bilbyai/intelligence-platform/assets/9511823/6a2c79c3-9f73-4d9b-8b2f-06ca69fda9e8)

It seems that our font is not loading in production or dev. Is this just me?

**Comment by betamax** [comment]
I had this too, it was fixed when I redeployed. Maybe this is the solution?

https://stackoverflow.com/a/72607368

I've added to my branch.
