### ISSUE TITLE
Update style of input fill

### ISSUE THREAD

**Issue by Mary-doagency** [bilbyai/intelligence-platform#70]
<img width="1148" alt="螢幕截圖 2024-02-19 下午5 05 02" src="https://github.com/bilbyai/intelligence-platform/assets/160113202/189c608e-7ead-4244-b982-9705552775aa">
<img width="125" alt="螢幕截圖 2024-02-19 下午5 07 59" src="https://github.com/bilbyai/intelligence-platform/assets/160113202/e99a7056-a45b-4915-b997-a8582c9ff7ae">

- del the black border (global update)

Please reference to this 
Search bar: [https://www.figma.com/file/F5cFiirOH7rkuMqtuBBDiK/BIP?type=design&node-id=1375-20264&mode=design&t=S0fuJmAt3l5Uvn0x-11](url)

Input: [https://www.figma.com/file/F5cFiirOH7rkuMqtuBBDiK/BIP?type=design&node-id=1189-17800&mode=design&t=S0fuJmAt3l5Uvn0x-11](url)

**Comment by betamax** [comment]
Should be done @kennethdo
